"""
    Constants related to scispace logger service
"""

import os

# LOG LEVEL RELATED CONSTANTS
ERROR = 'ERROR'
INFO = 'INFO'
WARNING = 'WARNING'
DEBUG = 'DEBUG'

# KINESIS RELATED CONSTANTS
DELIVERY_STREAM_NAME = os.getenv(
    'SCISPACE_LOGGER_DELIVERY_STREAM_NAME', 'scispace-server-logs')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_REGION_NAME = os.getenv('AWS_REGION_NAME', 'us-west-2')

# Client Related CONSTANTS
ENV = os.getenv('SCISPACE_LOGGER_ENV')
APP_NAME = os.getenv('SCISPACE_LOGGER_APP_NAME')
ENABLE_SCISPACE_LOGGER = os.getenv('ENABLE_SCISPACE_LOGGER')
